### ISSUE TITLE
only weak aliases are supported on darwin

### ISSUE THREAD

**Issue by divinerapier** [immunant/c2rust#112]
Question: Error on command `intercept-build make check` .

Output: 
```
xchecks/xchecks.c:5:21: error: only weak aliases are supported on darwin
    __attribute__ ((alias("__c2rust_hash_ldat_struct")));
```

**Comment by ahomescu** [comment]
I disabled most of the `xchecks.c` files (there is one in the libxml2 repo and one in tmux), they should compile on Mac OS now.

@divinerapier Let me know if you still run into problems.

**Comment by divinerapier** [comment]
@ahomescu thanks a lot, this problem has been solved. but i get another one when i run `./translate.py` after execute `./autogen.sh && ./configure && intercept-build make check`

``` sh
$ ./translate.py
Transpiling...
Traceback (most recent call last):
  File "./translate.py", line 234, in <module>
    move(TMUX_RS, MAIN_RS)
  File "./translate.py", line 192, in move
    return mv[mv_args].run()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/plumbum/commands/base.py", line 240, in run
    return p.run()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/plumbum/commands/base.py", line 201, in runner
    return run_proc(p, retcode, timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/plumbum/commands/processes.py", line 232, in run_proc
    return _check_process(proc, retcode, timeout, stdout, stderr)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/plumbum/commands/processes.py", line 23, in _check_process
    proc.verify(retcode, timeout, stdout, stderr)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/plumbum/machines/base.py", line 26, in verify
    stderr)
plumbum.commands.processes.ProcessExecutionError: Command line: ['/bin/mv', '/Users/myuser/Documents/code/rust/github.com/immunant/c2rust/examples/tmux/repo/tmux.rs', '/Users/myuser/Documents/code/rust/github.com/immunant/c2rust/examples/tmux/repo/rust/src/main.rs']
Exit code: 1
Stderr:  | mv: rename /Users/myuser/Documents/code/rust/github.com/immunant/c2rust/examples/tmux/repo/tmux.rs to /Users/myuser/Documents/code/rust/github.com/immunant/c2rust/examples/tmux/repo/rust/src/main.rs: No such file or directory

# myuser @ myuserdeMacBook-Pro in ~/Documents/code/rust/github.com/immunant/c2rust/examples/tmux on git:master o [10:43:48] C:1
$ stat /Users/myuser/Documents/code/rust/github.com/immunant/c2rust/examples/tmux/repo/tmux.rs
stat: /Users/myuser/Documents/code/rust/github.com/immunant/c2rust/examples/tmux/repo/tmux.rs: stat: No such file or directory
```
