### ISSUE TITLE
[ioq3] Transpiler panics on comments in `be_ai_char.c`

### ISSUE THREAD

**Issue by thedataking** [immunant/c2rust#157]
Reproducing:
```
RUST_BACKTRACE=1 c2rust transpile --emit-build-files --output-dir quake3-rs/quake3-ui compile_commands.json --filter be_ai_char  --overwrite-existing  -- -Wno-incompatible-pointer-types-discards-qualifiers
```

Backtrace:
```
Transpiling /home/perl/Work/ioq3/code/botlib/be_ai_char.c
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/libcore/option.rs:347:21
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.29/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.29/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:47
   3: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:36
   4: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:198
   5: std::panicking::default_hook
             at src/libstd/panicking.rs:212
   6: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:475
   7: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:382
   8: rust_begin_unwind
             at src/libstd/panicking.rs:309
   9: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
  10: core::panicking::panic
             at src/libcore/panicking.rs:49
  11: core::option::Option<T>::unwrap
             at /rustc/929b48ec98aaff2239257574b5897f419cec2647/src/libcore/macros.rs:12
  12: c2rust_transpile::rust_ast::comment_store::CommentStore::move_comments
             at c2rust-transpile/src/rust_ast/comment_store.rs:184
  13: c2rust_transpile::cfg::structures::StructureState::into_stmt::{{closure}}
             at c2rust-transpile/src/cfg/structures.rs:476
  14: core::option::Option<T>::unwrap_or_else
             at /rustc/929b48ec98aaff2239257574b5897f419cec2647/src/libcore/option.rs:388
  15: c2rust_transpile::cfg::structures::StructureState::into_stmt
             at c2rust-transpile/src/cfg/structures.rs:475
  16: c2rust_transpile::cfg::structures::StructureState::into_stmt
             at c2rust-transpile/src/cfg/structures.rs:469
  17: c2rust_transpile::cfg::structures::StructureState::into_stmt
             at c2rust-transpile/src/cfg/structures.rs:524
  18: c2rust_transpile::cfg::structures::StructureState::into_stmt
             at c2rust-transpile/src/cfg/structures.rs:445
  19: c2rust_transpile::cfg::structures::StructureState::into_stmt
             at c2rust-transpile/src/cfg/structures.rs:463
  20: c2rust_transpile::cfg::structures::StructureState::into_stmt
             at c2rust-transpile/src/cfg/structures.rs:469
  21: c2rust_transpile::cfg::structures::StructureState::into_stmt
             at c2rust-transpile/src/cfg/structures.rs:469
  22: c2rust_transpile::cfg::structures::StructureState::into_stmt
             at c2rust-transpile/src/cfg/structures.rs:469
  23: c2rust_transpile::cfg::structures::StructureState::into_stmt
             at c2rust-transpile/src/cfg/structures.rs:524
  24: c2rust_transpile::cfg::structures::StructureState::into_stmt
             at c2rust-transpile/src/cfg/structures.rs:445
  25: c2rust_transpile::cfg::structures::StructureState::into_stmt
             at c2rust-transpile/src/cfg/structures.rs:463
  26: c2rust_transpile::cfg::structures::StructureState::into_stmt
             at c2rust-transpile/src/cfg/structures.rs:469
  27: c2rust_transpile::cfg::structures::StructureState::into_stmt
             at c2rust-transpile/src/cfg/structures.rs:618
  28: c2rust_transpile::cfg::structures::StructureState::into_stmt
             at c2rust-transpile/src/cfg/structures.rs:445
  29: c2rust_transpile::cfg::structures::StructureState::into_stmt
             at c2rust-transpile/src/cfg/structures.rs:463
  30: c2rust_transpile::cfg::structures::structured_cfg
             at c2rust-transpile/src/cfg/structures.rs:25
  31: c2rust_transpile::translator::Translation::convert_cfg
             at c2rust-transpile/src/translator/mod.rs:2274
  32: c2rust_transpile::cfg::CfgBuilder::incrementally_reloop_subgraph
             at c2rust-transpile/src/cfg/mod.rs:1984
  33: c2rust_transpile::cfg::CfgBuilder::convert_stmt_help
             at c2rust-transpile/src/cfg/mod.rs:1903
  34: c2rust_transpile::cfg::CfgBuilder::convert_stmts_help::{{closure}}
             at c2rust-transpile/src/cfg/mod.rs:1353
  35: c2rust_transpile::cfg::CfgBuilder::with_scope
             at c2rust-transpile/src/cfg/mod.rs:1269
  36: c2rust_transpile::cfg::CfgBuilder::convert_stmts_help
             at c2rust-transpile/src/cfg/mod.rs:1343
  37: c2rust_transpile::cfg::Cfg<c2rust_transpile::cfg::Label,c2rust_transpile::cfg::StmtOrDecl>::from_stmts::{{closure}}
             at c2rust-transpile/src/cfg/mod.rs:593
  38: c2rust_transpile::translator::Translation::with_scope
             at c2rust-transpile/src/translator/mod.rs:4429
  39: c2rust_transpile::cfg::Cfg<c2rust_transpile::cfg::Label,c2rust_transpile::cfg::StmtOrDecl>::from_stmts
             at c2rust-transpile/src/cfg/mod.rs:591
  40: c2rust_transpile::translator::Translation::convert_function_body::{{closure}}
             at c2rust-transpile/src/translator/mod.rs:2293
  41: c2rust_transpile::translator::Translation::with_scope
             at c2rust-transpile/src/translator/mod.rs:4429
  42: c2rust_transpile::translator::Translation::convert_function_body
             at c2rust-transpile/src/translator/mod.rs:2292
  43: c2rust_transpile::translator::Translation::convert_function::{{closure}}
             at c2rust-transpile/src/translator/mod.rs:2122
  44: c2rust_transpile::translator::Translation::with_scope
             at c2rust-transpile/src/translator/mod.rs:4429
  45: c2rust_transpile::translator::Translation::convert_function
             at c2rust-transpile/src/translator/mod.rs:2031
  46: c2rust_transpile::translator::Translation::convert_decl
             at c2rust-transpile/src/translator/mod.rs:1734
  47: c2rust_transpile::translator::translate::{{closure}}
             at c2rust-transpile/src/translator/mod.rs:720
  48: scoped_tls::ScopedKey<T>::set
             at /cargo/registry/src/github.com-1ecc6299db9ec823/scoped-tls-1.0.0/src/lib.rs:137
  49: syntax::with_globals::{{closure}}
             at /rustc/929b48ec98aaff2239257574b5897f419cec2647/src/libsyntax/lib.rs:108
  50: scoped_tls::ScopedKey<T>::set
             at /cargo/registry/src/github.com-1ecc6299db9ec823/scoped-tls-1.0.0/src/lib.rs:137
  51: syntax::with_globals
             at /rustc/929b48ec98aaff2239257574b5897f419cec2647/src/libsyntax/lib.rs:107
  52: c2rust_transpile::translator::translate
             at c2rust-transpile/src/translator/mod.rs:541
  53: c2rust_transpile::transpile_single
             at c2rust-transpile/src/lib.rs:370
  54: c2rust_transpile::transpile::{{closure}}
             at c2rust-transpile/src/lib.rs:176
  55: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold::{{closure}}
             at /rustc/929b48ec98aaff2239257574b5897f419cec2647/src/libcore/iter/adapters/mod.rs:589
  56: <core::slice::Iter<T> as core::iter::traits::iterator::Iterator>::fold
             at /rustc/929b48ec98aaff2239257574b5897f419cec2647/src/libcore/slice/mod.rs:3178
  57: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold
             at /rustc/929b48ec98aaff2239257574b5897f419cec2647/src/libcore/iter/adapters/mod.rs:589
  58: core::iter::traits::iterator::Iterator::for_each
             at /rustc/929b48ec98aaff2239257574b5897f419cec2647/src/libcore/iter/traits/iterator.rs:604
  59: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::spec_extend
             at /rustc/929b48ec98aaff2239257574b5897f419cec2647/src/liballoc/vec.rs:1926
  60: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter
             at /rustc/929b48ec98aaff2239257574b5897f419cec2647/src/liballoc/vec.rs:1909
  61: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter
             at /rustc/929b48ec98aaff2239257574b5897f419cec2647/src/liballoc/vec.rs:1796
  62: core::iter::traits::iterator::Iterator::collect
             at /rustc/929b48ec98aaff2239257574b5897f419cec2647/src/libcore/iter/traits/iterator.rs:1466
  63: c2rust_transpile::transpile
             at c2rust-transpile/src/lib.rs:174
  64: c2rust_transpile::main
             at c2rust/src/bin/c2rust-transpile.rs:126
  65: std::rt::lang_start::{{closure}}
             at /rustc/929b48ec98aaff2239257574b5897f419cec2647/src/libstd/rt.rs:64
  66: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:49
  67: std::panicking::try::do_call
             at src/libstd/panicking.rs:294
  68: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:82
  69: std::panicking::try
             at src/libstd/panicking.rs:273
  70: std::panic::catch_unwind
             at src/libstd/panic.rs:388
  71: std::rt::lang_start_internal
             at src/libstd/rt.rs:48
  72: std::rt::lang_start
             at /rustc/929b48ec98aaff2239257574b5897f419cec2647/src/libstd/rt.rs:64
  73: main
  74: __libc_start_main
  75: _start
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by thedataking** [comment]
This comment seems to be the root of the problem. Deleting it avoids the panic.
```diff
diff --git a/code/botlib/be_ai_char.c b/code/botlib/be_ai_char.c
index 4adb2812..305a9608 100644
--- a/code/botlib/be_ai_char.c
+++ b/code/botlib/be_ai_char.c
@@ -313,7 +313,7 @@ bot_character_t *BotLoadCharacterFromFile(char *charfile, int skill)
                                                BotFreeCharacterStrings(ch);
                                                FreeMemory(ch);
                                                return NULL;
-                                       } //end else
+                                       }
                                } //end if
                                break;
                        } //end if
```
