### ISSUE TITLE
Build fails

### ISSUE THREAD

**Issue by samuela** [immunant/c2rust#187]
I'm installing c2rust following exactly the instructions provided in the readme, but it fails:

```
root@e581c80974df:/src# RUST_BACKTRACE=1 cargo +nightly-2019-10-04 install c2rust
    Updating crates.io index
  Installing c2rust v0.13.0
   Compiling libc v0.2.65
...
   Compiling itertools v0.8.1
error: failed to compile `c2rust v0.13.0`, intermediate artifacts can be found at `/tmp/cargo-installdotAug`

Caused by:
  failed to run custom build command for `c2rust-refactor v0.13.0`

Caused by:
  process didn't exit successfully: `/tmp/cargo-installdotAug/release/build/c2rust-refactor-dead6bcacbd887b2/build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'failed to run process_ast.py: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/libcore/result.rs:1165:5
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.37/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.37/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:76
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:60
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1028
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1412
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:64
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:196
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:210
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:473
  11: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:380
  12: rust_begin_unwind
             at src/libstd/panicking.rs:307
  13: core::panicking::panic_fmt
             at src/libcore/panicking.rs:84
  14: core::result::unwrap_failed
             at src/libcore/result.rs:1165
  15: build_script_build::process_ast
  16: build_script_build::main
  17: std::rt::lang_start::{{closure}}
  18: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:49
  19: std::panicking::try::do_call
             at src/libstd/panicking.rs:292
  20: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:80
  21: std::panicking::try
             at src/libstd/panicking.rs:271
  22: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  23: std::rt::lang_start_internal
             at src/libstd/rt.rs:48
  24: main
  25: __libc_start_main
  26: _start
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

root@e581c80974df:/src#
```

**Comment by samuela** [comment]
Or with `RUST_BACKTRACE=full`,

```
root@e581c80974df:/src# RUST_BACKTRACE=full cargo +nightly-2019-10-04 install c2rust
    Updating crates.io index
  Installing c2rust v0.13.0
   Compiling libc v0.2.65
   Compiling cc v1.0.46
   Compiling cfg-if v0.1.10
   Compiling proc-macro2 v1.0.6
   Compiling autocfg v0.1.7
   Compiling unicode-xid v0.2.0
   Compiling syn v1.0.7
   Compiling pkg-config v0.3.16
   Compiling serde v1.0.102
   Compiling lazy_static v1.4.0
   Compiling log v0.4.8
   Compiling memchr v2.2.1
   Compiling bitflags v1.2.1
   Compiling regex-syntax v0.6.12
   Compiling byteorder v1.3.2
   Compiling smallvec v0.6.11
   Compiling quick-error v1.2.2
   Compiling version_check v0.1.5
   Compiling unicode-width v0.1.6
   Compiling semver-parser v0.7.0
   Compiling proc-macro2 v0.4.30
   Compiling matches v0.1.8
   Compiling glob v0.3.0
   Compiling failure_derive v0.1.6
   Compiling ryu v1.0.2
   Compiling rustc-demangle v0.1.16
   Compiling ansi_term v0.11.0
   Compiling strsim v0.8.0
   Compiling termcolor v1.0.5
   Compiling vec_map v0.8.1
   Compiling unicode-xid v0.1.0
   Compiling getrandom v0.1.13
   Compiling yaml-rust v0.3.5
   Compiling syn v0.15.44
   Compiling percent-encoding v1.0.1
   Compiling itoa v0.4.4
   Compiling ucd-trie v0.1.2
   Compiling winapi v0.3.8
   Compiling bindgen v0.51.1
   Compiling ppv-lite86 v0.2.6
   Compiling openssl-probe v0.1.2
   Compiling cgmath v0.16.1
   Compiling typenum v1.11.2
   Compiling curl v0.4.25
   Compiling same-file v1.0.5
   Compiling maplit v1.0.2
   Compiling shlex v0.1.1
   Compiling foreign-types-shared v0.1.1
   Compiling approx v0.1.1
   Compiling crc32fast v1.2.0
   Compiling peeking_take_while v0.1.2
   Compiling openssl v0.10.25
   Compiling fnv v1.0.6
   Compiling rgb v0.8.14
   Compiling adler32 v1.0.4
   Compiling half v1.4.0
   Compiling hex v0.3.2
   Compiling unicode-segmentation v1.3.0
   Compiling remove_dir_all v0.5.2
   Compiling glob v0.2.11
   Compiling c2rust-ast-builder v0.13.0
   Compiling rustc-workspace-hack v1.0.0
   Compiling c2rust-refactor v0.13.0
   Compiling home v0.3.4
   Compiling lazycell v1.2.1
   Compiling shell-escape v0.1.4
   Compiling bytesize v1.0.0
   Compiling either v1.5.3
   Compiling json v0.11.15
   Compiling pathdiff v0.1.0
   Compiling dtoa v0.4.4
   Compiling diff v0.1.11
   Compiling slotmap v0.3.0
   Compiling strum v0.15.0
   Compiling cmake v0.1.42
   Compiling libnghttp2-sys v0.1.2
   Compiling backtrace-sys v0.1.32
   Compiling libloading v0.5.2
   Compiling rlua v0.16.3
   Compiling num-traits v0.2.8
   Compiling num-integer v0.1.41
   Compiling indexmap v1.3.0
   Compiling openssl-sys v0.9.52
   Compiling libz-sys v1.0.25
   Compiling curl-sys v0.4.23
   Compiling libssh2-sys v0.2.13
   Compiling libgit2-sys v0.7.11
   Compiling thread_local v0.3.6
   Compiling crossbeam-utils v0.6.6
   Compiling unicode-normalization v0.1.8
   Compiling humantime v1.3.0
   Compiling nom v4.2.3
   Compiling textwrap v0.11.0
   Compiling unicode-bidi v0.3.4
   Compiling clang-sys v0.28.1
   Compiling pest v2.1.2
   Compiling c2-chacha v0.2.3
   Compiling walkdir v2.2.9
   Compiling foreign-types v0.3.2
   Compiling miniz_oxide v0.3.5
   Compiling heck v0.3.1
error: failed to compile `c2rust v0.13.0`, intermediate artifacts can be found at `/tmp/cargo-install8JjwoJ`

Caused by:
  failed to run custom build command for `c2rust-refactor v0.13.0`

Caused by:
  process didn't exit successfully: `/tmp/cargo-install8JjwoJ/release/build/c2rust-refactor-dead6bcacbd887b2/build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'failed to run process_ast.py: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/libcore/result.rs:1165:5
stack backtrace:
   0:     0x55f20b356cf4 - backtrace::backtrace::libunwind::trace::h19774dea45f5192e
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.37/src/backtrace/libunwind.rs:88
   1:     0x55f20b356cf4 - backtrace::backtrace::trace_unsynchronized::h17947fc1cb72b217
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.37/src/backtrace/mod.rs:66
   2:     0x55f20b356cf4 - std::sys_common::backtrace::_print_fmt::h7b3edf3a4bfcedd3
                               at src/libstd/sys_common/backtrace.rs:76
   3:     0x55f20b356cf4 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h3ea3134b71160a75
                               at src/libstd/sys_common/backtrace.rs:60
   4:     0x55f20b37435c - core::fmt::write::hb50f65a11f629d84
                               at src/libcore/fmt/mod.rs:1028
   5:     0x55f20b355097 - std::io::Write::write_fmt::h30970d8ac223811c
                               at src/libstd/io/mod.rs:1412
   6:     0x55f20b358ff5 - std::sys_common::backtrace::_print::h48f10c5c50d0e0d7
                               at src/libstd/sys_common/backtrace.rs:64
   7:     0x55f20b358ff5 - std::sys_common::backtrace::print::h93ea115513ee061c
                               at src/libstd/sys_common/backtrace.rs:49
   8:     0x55f20b358ff5 - std::panicking::default_hook::{{closure}}::hbf5672c85fe44d10
                               at src/libstd/panicking.rs:196
   9:     0x55f20b358ce6 - std::panicking::default_hook::h5d2ce66938b54bc6
                               at src/libstd/panicking.rs:210
  10:     0x55f20b359645 - std::panicking::rust_panic_with_hook::h60898b7fda675e17
                               at src/libstd/panicking.rs:473
  11:     0x55f20b3591e2 - std::panicking::continue_panic_fmt::h46da20a693d55410
                               at src/libstd/panicking.rs:380
  12:     0x55f20b3590d6 - rust_begin_unwind
                               at src/libstd/panicking.rs:307
  13:     0x55f20b371e2a - core::panicking::panic_fmt::h4ddf3c5f8367e071
                               at src/libcore/panicking.rs:84
  14:     0x55f20b371f27 - core::result::unwrap_failed::h5541759cb38b9dc1
                               at src/libcore/result.rs:1165
  15:     0x55f20b34d6ff - build_script_build::process_ast::h9dbcea5f24cd3630
  16:     0x55f20b34d886 - build_script_build::main::h883bfd925a662b6a
  17:     0x55f20b34cf63 - std::rt::lang_start::{{closure}}::hf3a803cd74235b84
  18:     0x55f20b3590c3 - std::rt::lang_start_internal::{{closure}}::hf12e05489c25df97
                               at src/libstd/rt.rs:49
  19:     0x55f20b3590c3 - std::panicking::try::do_call::h3a3b1a8c0e4ac389
                               at src/libstd/panicking.rs:292
  20:     0x55f20b35f6da - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:80
  21:     0x55f20b359b3d - std::panicking::try::h751f69a77cebe6cb
                               at src/libstd/panicking.rs:271
  22:     0x55f20b359b3d - std::panic::catch_unwind::ha68f66b42735c752
                               at src/libstd/panic.rs:394
  23:     0x55f20b359b3d - std::rt::lang_start_internal::hf8d6eae1132f8119
                               at src/libstd/rt.rs:48
  24:     0x55f20b34e272 - main
  25:     0x7fe4e9e5fb97 - __libc_start_main
  26:     0x55f20b34ce7a - _start
  27:                0x0 - <unknown>

root@e581c80974df:/src#
```

**Comment by samuela** [comment]
I'm running Ubuntu 18.04 in docker.

**Comment by rinon** [comment]
Do you have python3 installed?

**Comment by thedataking** [comment]
We have a Ubuntu 18.04 docker image that is fully provisioned for c2rust: `immunant/c2rust:ubuntu-bionic-latest`.

**Comment by samuela** [comment]
@rinon python3 was in fact the isseu
