### ISSUE TITLE
thread 'main' panicked at 'slice index starts at 1 but ends at 0'

### ISSUE THREAD

**Issue by bburdette** [immunant/c2rust#213]
Tried c2rust out on master, (commit 85fc7b730a2e3e0c53089deca817f535f925eef6), and on tag 0.13.0.  Result is below.

If you want, you can reproduce this in the c2rust branch of this repo:

https://github.com/chronopoulos/cyclophone/tree/c2rust/cpp/cyclosensors

There's a compile_commands.json there which was generated with bear like so:

```
> nix-shell -p liblo
> bear g++ -O2 -o cyclosensors main.cpp spidevice.cpp cyclomap.cpp -llo
```

And here's the error:

```
[nix-shell:~/code/cyclophone/cpp/cyclosensors/rust]$ RUST_BACKTRACE=1 ./c2rust transpile ../compile_commands.json 
thread 'main' panicked at 'slice index starts at 1 but ends at 0', src/libcore/slice/mod.rs:2589:5
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.37/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.37/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:76
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:60
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1028
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1412
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:64
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:196
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:210
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:473
  11: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:380
  12: rust_begin_unwind
             at src/libstd/panicking.rs:307
  13: core::panicking::panic_fmt
             at src/libcore/panicking.rs:84
  14: core::slice::slice_index_order_fail
             at src/libcore/slice/mod.rs:2589
  15: <core::ops::range::Range<usize> as core::slice::SliceIndex<[T]>>::index
             at /rustc/032a53a06ce293571e51bbe621a5c480e8a28e95/src/libcore/slice/mod.rs:2764
  16: <core::ops::range::RangeFrom<usize> as core::slice::SliceIndex<[T]>>::index
             at /rustc/032a53a06ce293571e51bbe621a5c480e8a28e95/src/libcore/slice/mod.rs:2847
  17: core::slice::<impl core::ops::index::Index<I> for [T]>::index
             at /rustc/032a53a06ce293571e51bbe621a5c480e8a28e95/src/libcore/slice/mod.rs:2566
  18: <alloc::vec::Vec<T> as core::ops::index::Index<I>>::index
             at /rustc/032a53a06ce293571e51bbe621a5c480e8a28e95/src/liballoc/vec.rs:1816
  19: c2rust_transpile::transpile
             at c2rust-transpile/src/lib.rs:226
  20: c2rust_transpile::main
             at c2rust/src/bin/c2rust-transpile.rs:126
  21: std::rt::lang_start::{{closure}}
             at /rustc/032a53a06ce293571e51bbe621a5c480e8a28e95/src/libstd/rt.rs:64
  22: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:49
  23: std::panicking::try::do_call
             at src/libstd/panicking.rs:292
  24: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:80
  25: std::panicking::try
             at src/libstd/panicking.rs:271
  26: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  27: std::rt::lang_start_internal
             at src/libstd/rt.rs:48
  28: std::rt::lang_start
             at /rustc/032a53a06ce293571e51bbe621a5c480e8a28e95/src/libstd/rt.rs:64
  29: main
  30: __libc_start_main
  31: _start
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by thedataking** [comment]
Hey @bburdette, thanks for opening an issue. We do not support C++ code at the moment. Adding support would be a lot of work and right now we are focused on supporting as much of C as possible and refactoring it to generate safer and cleaner C. That said, your message is helpful because it highlights that we should provide a much better error message if the input is C++ code.

**Comment by bburdette** [comment]
Thanks for the prompt response.  This answers my question about C++ support!
