### ISSUE TITLE
unrecongized type

### ISSUE THREAD

**Issue by valarauca** [immunant/c2rust#229]
# Background

I wanted to give `c2rust` a spin so I picked some low hanging fruits namely [`lz4`](https://github.com/lz4/lz4) as its source is relatively small.

# Issue

I built my 

<details><summary>compile_commands.json</summary>
<p>

```json
[
    {
        "arguments": [
            "cc",
            "-c",
            "-DXXH_NAMESPACE=LZ4_",
            "-O3",
            "-Wall",
            "-Wextra",
            "-Wcast-qual",
            "-Wcast-align",
            "-Wshadow",
            "-Wswitch-enum",
            "-Wdeclaration-after-statement",
            "-Wstrict-prototypes",
            "-Wundef",
            "-Wpointer-arith",
            "-Wstrict-aliasing=1",
            "xxhash.c"
        ],
        "directory": "/Users/wclaeder/Documents/c_projects/lz4/lib",
        "file": "xxhash.c"
    },
    {
        "arguments": [
            "cc",
            "-c",
            "-DXXH_NAMESPACE=LZ4_",
            "-O3",
            "-Wall",
            "-Wextra",
            "-Wcast-qual",
            "-Wcast-align",
            "-Wshadow",
            "-Wswitch-enum",
            "-Wdeclaration-after-statement",
            "-Wstrict-prototypes",
            "-Wundef",
            "-Wpointer-arith",
            "-Wstrict-aliasing=1",
            "lz4frame.c"
        ],
        "directory": "/Users/wclaeder/Documents/c_projects/lz4/lib",
        "file": "lz4frame.c"
    },
    {
        "arguments": [
            "cc",
            "-c",
            "-DXXH_NAMESPACE=LZ4_",
            "-O3",
            "-Wall",
            "-Wextra",
            "-Wcast-qual",
            "-Wcast-align",
            "-Wshadow",
            "-Wswitch-enum",
            "-Wdeclaration-after-statement",
            "-Wstrict-prototypes",
            "-Wundef",
            "-Wpointer-arith",
            "-Wstrict-aliasing=1",
            "lz4.c"
        ],
        "directory": "/Users/wclaeder/Documents/c_projects/lz4/lib",
        "file": "lz4.c"
    },
    {
        "arguments": [
            "cc",
            "-c",
            "-DXXH_NAMESPACE=LZ4_",
            "-O3",
            "-Wall",
            "-Wextra",
            "-Wcast-qual",
            "-Wcast-align",
            "-Wshadow",
            "-Wswitch-enum",
            "-Wdeclaration-after-statement",
            "-Wstrict-prototypes",
            "-Wundef",
            "-Wpointer-arith",
            "-Wstrict-aliasing=1",
            "lz4hc.c"
        ],
        "directory": "/Users/wclaeder/Documents/c_projects/lz4/lib",
        "file": "lz4hc.c"
    }
]
```

</p>
</details>

Then I blindly run `c2rust transpile compile_commands.json` within the top level of `lz4` directory and I see:

<details><summary>command output</summary>
<p>

```
Transpiling xxhash.c
warning: Missing type 140566101266720 for node: AstNode { tag: TagVarDecl, children: [None], loc: SrcSpan { fileid: 43, begin_line: 328, begin_column: 22, end_line: 328, end_column: 22 }, type_id: Some(140566101266720), rvalue: LValue, macro_expansions: [], extras: [Text("__compar"), Bool(false), Bool(false), Bool(false), Bool(true), Array([Text("noescape")])] }
Exported Clang AST was invalid. Check warnings above for unimplemented features.
--> /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/stdlib.h:328:22
 [-Wclang-ast]
warning: Missing type 140566101263984 for node: AstNode { tag: TagVarDecl, children: [None], loc: SrcSpan { fileid: 43, begin_line: 320, begin_column: 22, end_line: 320, end_column: 22 }, type_id: Some(140566101263984), rvalue: LValue, macro_expansions: [], extras: [Text("__compar"), Bool(false), Bool(false), Bool(false), Bool(true), Array([Text("noescape")])] }
Exported Clang AST was invalid. Check warnings above for unimplemented features.
--> /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/stdlib.h:320:22
 [-Wclang-ast]
warning: Missing type 140566101261328 for node: AstNode { tag: TagVarDecl, children: [None], loc: SrcSpan { fileid: 43, begin_line: 313, begin_column: 22, end_line: 313, end_column: 22 }, type_id: Some(140566101261328), rvalue: LValue, macro_expansions: [], extras: [Text("__compar"), Bool(false), Bool(false), Bool(false), Bool(true), Array([Text("noescape")])] }
Exported Clang AST was invalid. Check warnings above for unimplemented features.
--> /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/stdlib.h:313:22
 [-Wclang-ast]
warning: Missing type 140566101270272 for node: AstNode { tag: TagVarDecl, children: [None], loc: SrcSpan { fileid: 43, begin_line: 336, begin_column: 22, end_line: 336, end_column: 22 }, type_id: Some(140566101270272), rvalue: LValue, macro_expansions: [], extras: [Text("__compar"), Bool(false), Bool(false), Bool(false), Bool(true), Array([Text("noescape")])] }
Exported Clang AST was invalid. Check warnings above for unimplemented features.
--> /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/stdlib.h:336:22
 [-Wclang-ast]
thread 'main' panicked at 'Could not find CTypeId(1578) in TypedAstContext', /Users/wclaeder/.cargo/registry/src/github.com-1ecc6299db9ec823/c2rust-transpile-0.14.0/src/c_ast/mod.rs:796:21
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

</p>
</details>

Now the panic in question

```
thread 'main' panicked at 'Could not find CTypeId(1578) in TypedAstContext', /Users/wclaeder/.cargo/registry/src/github.com-1ecc6299db9ec823/c2rust-transpile-0.14.0/src/c_ast/mod.rs:796:21
```

Seems to come from the [`Index<CTypeId>`](https://github.com/immunant/c2rust/blob/9f9d86ec86daa2341fd81645d5a661175df62046/c2rust-transpile/src/c_ast/mod.rs#L801-#L810) (I am linking to `^HEAD`, I compiled targetting `0.14.0`, and the `impl Index<_>` code appears to moved a couple lines).

I figured I should then look at what is generating these, namely the invalid AST (which is the standard library?)

They mostly seem to be coming sort prototypes within `stdlib.h`, or are the warning unrelated to the final type-mistatch? 

```C
int      mergesort_b(void *__base, size_t __nel, size_t __width,
             int (^ _Nonnull __compar)(const void *, const void *) __sort_noescape)
             __OSX_AVAILABLE_STARTING(__MAC_10_6, __IPHONE_3_2);
```

---

What is the remediation for this? 

Like is there anything I can do the source to assist `c2rust`?

**Comment by valarauca** [comment]
It worked!

sorry for the bother.

I switched the command to

```sh
c2rust transpile compile_commands.json -- -fno-blocks
```

**Comment by thedataking** [comment]
Reopening since it shouldn't be necessary to pass -fno-blocks on macOS.

**Comment by valarauca** [comment]
@thedataking 

Maybe expose a `--use-blocks` flag in the `c2rust` command line for OSX?

 `__BLOCKS__` is part of the MacOS SDK, and supporting it maybe relevant for software which depends on specific MacOS features?

I'm honestly not sure. I didn't find out about `-fno-blocks` or `__BLOCKS__` until yesterday. I'm not sure if totally disabling it completely is heavy handed or not.

**Comment by thedataking** [comment]
Hi @valarauca, it is heavy-handed to force the feature off but we're a small team and have to focus on the things that are most likely to drive the project forward. As such, rudimentary C++ support would probably be a higher priority than supporting blocks on macOS (we haven't run into any feature that needs it as of yet). That said, our number one priority is to improve the quality of the Rust we output (e.g. using safe Rust types where possible vs. using raw pointers, enhancing readability) so that's where our focus will be for the foreseeable future – absent a super compelling reason to support blocks 🤠

**Comment by valarauca** [comment]
No worries, just double checking. 

Yeah, it does appear to close a number of issues. So while heavy-handed it does seem like the right move.
