### ISSUE TITLE
TypedAstContext Panic - Could not find CTypeId / CStmtId.

### ISSUE THREAD

**Issue by ralfbiedert** [immunant/c2rust#231]
Hi,

I'm experimenting with transpiling [fann](https://github.com/libfann/fann). Setting up the project on macOS and Linux each worked fine via `cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=1 .` and produces a `compile_commands.json`.

However, invoking `c2rust transpile compile_commands.json` gives a series of error messages and eventual panic I can't really decipher:

On macOS I receive (with some output omitted):

```
warning: Skipping duplicate compilation cmd for /Users/rb/Documents/Development/Source/_thirdparty/fann/src/floatfann.c
warning: Skipping duplicate compilation cmd for /Users/rb/Documents/Development/Source/_thirdparty/fann/src/fixedfann.c
warning: Skipping duplicate compilation cmd for /Users/rb/Documents/Development/Source/_thirdparty/fann/src/floatfann.c
warning: Skipping duplicate compilation cmd for /Users/rb/Documents/Development/Source/_thirdparty/fann/src/floatfann.c
warning: Skipping duplicate compilation cmd for /Users/rb/Documents/Development/Source/_thirdparty/fann/src/doublefann.c
Additional Clang arguments:
Transpiling floatfann.c
warning: Missing type 140340826817936 for node: AstNode { tag: TagVarDecl, children: [None], loc: SrcSpan { fileid: 64, begin_line: 313, begin_column: 22, end_line: 313, end_column: 22 }, type_id: Some(140340826817936), rvalue: LValue, macro_expansions: [], extras: [Text("__compar"), Bool(false), Bool(false), Bool(false), Bool(true), Array([Text("noescape")])] }
Exported Clang AST was invalid. Check warnings above for unimplemented features.
--> /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/stdlib.h:313:22
 [-Wclang-ast]
warning: Missing type 140340826833472 for node: AstNode { tag: TagVarDecl, children: [None], loc: SrcSpan { fileid: 64, begin_line: 336, begin_column: 22, end_line: 336, end_column: 22 }, type_id: Some(140340826833472), rvalue: LValue, macro_expansions: [], extras: [Text("__compar"), Bool(false), Bool(false), Bool(false), Bool(true), Array([Text("noescape")])] }
Exported Clang AST was invalid. Check warnings above for unimplemented features.
--> /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/stdlib.h:336:22
 [-Wclang-ast]
warning: Missing type 140340826823296 for node: AstNode { tag: TagVarDecl, children: [None], loc: SrcSpan { fileid: 64, begin_line: 328, begin_column: 22, end_line: 328, end_column: 22 }, type_id: Some(140340826823296), rvalue: LValue, macro_expansions: [], extras: [Text("__compar"), Bool(false), Bool(false), Bool(false), Bool(true), Array([Text("noescape")])] }
Exported Clang AST was invalid. Check warnings above for unimplemented features.
--> /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/stdlib.h:328:22
 [-Wclang-ast]
warning: Missing type 140340826820576 for node: AstNode { tag: TagVarDecl, children: [None], loc: SrcSpan { fileid: 64, begin_line: 320, begin_column: 22, end_line: 320, end_column: 22 }, type_id: Some(140340826820576), rvalue: LValue, macro_expansions: [], extras: [Text("__compar"), Bool(false), Bool(false), Bool(false), Bool(true), Array([Text("noescape")])] }
Exported Clang AST was invalid. Check warnings above for unimplemented features.
--> /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/stdlib.h:320:22
 [-Wclang-ast]
thread 'main' panicked at 'Could not find CTypeId(3706) in TypedAstContext', /Users/rb/.cargo/registry/src/github.com-1ecc6299db9ec823/c2rust-transpile-0.14.0/src/c_ast/mod.rs:796:21
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

While on Linux it gives:

```
Additional Clang arguments:
In file included from /home/rb/source/_thirdparty/fann/src/floatfann.c:26:
/home/rb/source/_thirdparty/fann/src/fann_io.c:618:5: warning: taking address of packed member 'activation_steepness' of class or structure 'fann_neuron' may result in an unaligned pointer value [-Waddress-of-packed-member]
                        &neuron_it->activation_steepness) != 3)
                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /home/rb/source/_thirdparty/fann/src/floatfann.c:29:
/home/rb/source/_thirdparty/fann/src/fann_error.c:116:15: warning: passing an object that undergoes default argument promotion to 'va_start' has undefined behavior [-Wvarargs]
        va_start(ap, errno_f);
                     ^
/home/rb/source/_thirdparty/fann/src/fann_error.c:106:71: note: parameter of type 'const enum fann_errno_enum' is declared here
void fann_error(struct fann_error *errdat, const enum fann_errno_enum errno_f, ...)
                                                                      ^
...

2 warnings generated.
Transpiling floatfann.c
warning: Missing child 93949975582000 of node AstNode { tag: TagCompoundStmt, children: [Some(93949975582000)], loc: SrcSpan { fileid: 65, begin_line: 53, begin_column: 3, end_line: 68, end_column: 4 }, type_id: None, rvalue: LValue, macro_expansions: [], extras: [] }
Exported Clang AST was invalid. Check warnings above for unimplemented features.
--> /home/rb/source/_thirdparty/fann/src/parallel_fann.c:53:3
 [-Wclang-ast]
warning: Missing child 93949975669056 of node AstNode { tag: TagCompoundStmt, children: [Some(93949975669056)], loc: SrcSpan { fileid: 65, begin_line: 259, begin_column: 3, end_line: 324, end_column: 3 }, type_id: None, rvalue: LValue, macro_expansions: [], extras: [] }
Exported Clang AST was invalid. Check warnings above for unimplemented features.
--> /home/rb/source/_thirdparty/fann/src/parallel_fann.c:259:3
 [-Wclang-ast]
warning: Missing child 93949972914616 of node AstNode { tag: TagCompoundStmt, children: [Some(93949972884112), Some(93949972884392), Some(93949972884672), Some(93949972884872), Some(93949972885160), Some(93949972885448), Some(93949972885624), Some(93949972885960), Some(93949972886344), Some(93949972886520), Some(93949972886856), Some(93949972887192), Some(93949972887528), Some(93949972887864), Some(93949972888152), Some(93949972888480), Some(93949972889848), Some(93949972890120), Some(93949972890376), Some(93949972890552), Some(93949972890704), Some(93949972914616)], loc: SrcSpan { fileid: 65, begin_line: 378, begin_column: 5, end_line: 477, end_column: 5 }, type_id: None, rvalue: LValue, macro_expansions: [], extras: [] }
Exported Clang AST was invalid. Check warnings above for unimplemented features.
--> /home/rb/source/_thirdparty/fann/src/parallel_fann.c:378:5
 [-Wclang-ast]
warning: Missing child 93949975624232 of node AstNode { tag: TagCompoundStmt, children: [Some(93949975624232)], loc: SrcSpan { fileid: 65, begin_line: 140, begin_column: 3, end_line: 187, end_column: 4 }, type_id: None, rvalue: LValue, macro_expansions: [], extras: [] }
Exported Clang AST was invalid. Check warnings above for unimplemented features.
--> /home/rb/source/_thirdparty/fann/src/parallel_fann.c:140:3
 [-Wclang-ast]

 ...

 thread 'main' panicked at 'Could not find CStmtId(36286) in TypedAstContext', /home/rb/.cargo/registry/src/github.com-1ecc6299db9ec823/c2rust-transpile-0.14.0/src/c_ast/mod.rs:839:21

```

The actual output might be slightly different between these two because I tried to comment out some lines that were (seemingly) related, but in the end the transpilation always panics, even on a vanialla copy.  

Apart from the bug report I would also be very grateful for any hints if and how I could work around this issue!

I am using `C2Rust 0.14.0` and I followed the instructions for installing with `nightly-2019-12-05`.

**Comment by thedataking** [comment]
Hi @ralfbiedert,

Seems like you're hitting an issue related to an Apple extention to C (blocks) that was fixed on master. You can confirm that this is indeed the case by passing `-fno-blocks` as an extra argument to clang while transpiling. If invoking the transpiler like below solves the issue, then it has been fixed on `master`:

    c2rust transpile compile_commands.json -- -fno-blocks


See issue #229 for more info.

**Comment by ralfbiedert** [comment]
Thank you so much, that fixed my problem on macOS!
