### ISSUE TITLE
Demo on Website does not work anymore

### ISSUE THREAD

**Issue by barafael** [immunant/c2rust#701]
I'm getting in the console:

```
Uncaught SyntaxError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON
    at Function.parse [as parseJSON] (<anonymous>)
    at Object.<anonymous> (translate.js:122:26)
    at u (jquery.min.js:2:27457)
    at Object.fireWith [as rejectWith] (jquery.min.js:2:28202)
    at k (jquery.min.js:2:77676)
    at XMLHttpRequest.<anonymous> (jquery.min.js:2:79907)
```

**Comment by kkysen** [comment]
The response is

```html
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>503 Service Unavailable</title>
</head><body>
<h1>Service Unavailable</h1>
<p>The server is temporarily unable to service your
request due to maintenance downtime or capacity
problems. Please try again later.</p>
<hr>
<address>Apache/2.4.18 (Ubuntu) Server at c2rust.com Port 443</address>
</body></html>
```

It seems like the translator server is down; I'm not sure why.

**Comment by kkysen** [comment]
[c2rust.com](https://c2rust.com/) has been fixed by @rinon now, and I believe it also uses the latest [crates.io release](https://crates.io/crates/c2rust) now, too.
